//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCoerceDate
    {
        public int SCourseDateId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime PlanedFinishDate { get; set; }
        public int CourseId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
